use_frameworks!

platform :ios, '9.0'

target 'detalhesBit_Example' do
  pod 'detalhesBit', :path => '../'

  target 'detalhesBit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
